In [1]:
import numpy as np

In [10]:
#first exercise(7)
array=np.array([-10.2,122.2,0.2,-0.03])
array=abs(array)
#result should be the same if using abs or the numpy function
array2=np.copy(array)
array2=np.absolute(array2)
print array
print array2

[  1.02000000e+01   1.22200000e+02   2.00000000e-01   3.00000000e-02]
[  1.02000000e+01   1.22200000e+02   2.00000000e-01   3.00000000e-02]


In [16]:
#second exercise(11)
#define the arrays
matrix=np.array([[ 0.44349753, 0.81043761, 0.00771825],
[ 0.64004088, 0.86774612, 0.19944667],
[ 0.61520091, 0.24796788, 0.93798297],
[ 0.22156999, 0.61318856, 0.82348994],
[ 0.91324026, 0.13411297, 0.00622696]])
matrix2=np.array([[ 0.73873542, 0.06448186],
[ 0.90974982, 0.06409165],
[ 0.22321268, 0.39147412]])
def multiplicacion(a,b):
    c=a.dot(b)
    print c
multiplicacion(matrix,matrix2)

[[ 1.06664562  0.08356132]
 [ 1.30677177  0.17496452]
 [ 0.88942913  0.42275803]
 [ 0.90534318  0.37596251]
 [ 0.79804211  0.06992065]]


In [20]:
#exercise 3(19 of math )
#calculate the mean of a matrix in rows
matrix=np.array([[10, 30],
[20, 60]])
meanrow=np.mean(matrix,axis=0)
print meanrow
#calculate the mean of a matrix in columns
meancol=np.mean(matrix,axis=1)
print meancol

[ 15.  45.]
[ 20.  40.]


In [24]:
#exercise 4(20 of math)
#generate a random numbers array
alea=np.random.rand(1000)
avg=np.mean(alea)
std=np.std(alea)
var=np.var(alea)
print avg, std, var

0.48858673683 0.284134137823 0.0807322082763
